# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - cron: "0 8 * * *"
name: CodeceptJS example reporting

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  reporting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Dependencies installing
        run: npm i
      - name: Generate unique run value
        id: generate-run
        run: echo "::set-output name=run_value::$(date +%s)"
      - run: npx codeceptjs run
        env:
          TESTOMATIO: "${{ secrets.TESTOMATIO }}"
          TESTOMATIO_URL: "${{ secrets.TESTOMATIO_URL }}"
          CODECEPT_GROUP_TESTS: "${{ secrets.CODECEPT_GROUP_TESTS }}"
