# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - cron: "0 8 * * *"
name: CodeceptJS example reporting results

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  reporting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Dependencies installing
        run: npm ci
      - name: Test executing
        id: test-incorrect
        continue-on-error: true
        run: |
          npx codeceptjs run > test-results.txt
          fail_tests=$(grep -oP '^\d+ failed' test-results.txt | grep -oP '\d+')
          echo "Number of failed tests: $fail_tests"
          if [ "$fail_tests" -gt 1 ]; then
            echo "More than 1 failed tests. Exiting with error."
            exit 1
          fi
        env:
          TESTOMATIO: "${{ secrets.TESTOMATIO }}"
          TESTOMATIO_URL: "${{ secrets.TESTOMATIO_URL }}"
          CODECEPT_GROUP_TESTS: "${{ secrets.CODECEPT_GROUP_TESTS }}"
      - name: Invert success and failure
        run: echo ${{ steps.test-incorrect.outcome }}

#run: if [[ ${{ steps.test-incorrect.outcome }} == "failure" ]]; then exit 0; else exit 1; fi